name: PR Automation

on:
  pull_request:
    types: [closed, reopened, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pr_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 自动关闭带有特定标签的 PR
      - name: Auto close labeled PR
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'labeled' &&
          contains(
            '❌ 忽略,❌ 拒绝 / 放弃,❌ 暂无计划,❌ 第三方,❌ 重复,😂 移交上游',
            github.event.label.name
          )
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          comment: false
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

      # 处理已合并的 PR
      - name: Remove progress labels from merged PR
        if: github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: '⭕ 等待处理,🚧 正在处理,🕑 等待合并,🕑 等待前置'
          repo-token: ${{ secrets.BOT }}

      - name: Add completed label to merged PR
        if: github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: '👌 完成'
          repo-token: ${{ secrets.BOT }}

      # 处理重新打开的 PR
      - name: Cleanup labels on reopened PR
        if: github.event.action == 'reopened'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: '❌ 忽略,❌ 拒绝 / 放弃,❌ 暂无计划,❌ 第三方,❌ 重复'
          repo-token: ${{ secrets.BOT }}