name: PR Automation

on:
  pull_request:
    types: [closed, reopened, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pr_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto close PR
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'labeled' &&
          contains(
            '❌ 忽略,❌ 拒绝 / 放弃,❌ 暂无计划,❌ 第三方,❌ 重复,😂 移交上游',
            github.event.label.name
          )
        env:
          GH_TOKEN: ${{ secrets.BOT }}
        run: gh pr close ${{ github.event.number }}

      - name: Cleanup merged PR
        if: github.event.action == 'closed' && github.event.pull_request.merged
        env:
          GH_TOKEN: ${{ secrets.BOT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          export GH_TOKEN
          printf '%s\n' '⭕ 等待处理' '🚧 正在处理' '🕑 等待合并' '🕑 等待前置' | while read -r label; do
            gh issue edit $PR_NUMBER --remove-label "$label" || true
          done
          gh issue edit $PR_NUMBER --add-label "👌 完成"

      - name: Cleanup reopened PR
        if: github.event.action == 'reopened'
        env:
          GH_TOKEN: ${{ secrets.BOT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          export GH_TOKEN
          printf '%s\n' '❌ 忽略' '❌ 拒绝 / 放弃' '❌ 暂无计划' '❌ 第三方' '❌ 重复' | while read -r label; do
            gh issue edit $PR_NUMBER --remove-label "$label" || true
          done