name: PR Automation

on:
  pull_request:
    types: [closed, reopened]

jobs:
  handle_pr_events:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Remove old labels on merge
        if: github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.BOT }}
          labels: |
            ⭕ 等待处理
            🚧 正在处理
            🕑 等待合并
            🕑 等待前置

      - name: Add completed label
        if: github.event.action == 'closed' && github.event.pull_request.merged
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.BOT }}
          labels: 👌 完成

      
      - name: Clean labels on reopen
        if: github.event.action == 'reopened'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.BOT }}
          labels: |
            ❌ 忽略
            ❌ 拒绝 / 放弃
            ❌ 暂无计划
            ❌ 第三方
            ⭕ 等待处理
            ❌ 重复
