name: Issue Closed

on:
  issues:
    types: [closed]

jobs:
  process-closed-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Validate and handle completed issue
        if: github.event.issue.state_reason == 'completed' &&
          github.event.sender.login != 'PCL-Community-Bot'
        env:
          BOT_TOKEN: ${{ secrets.BOT }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository.split('/')[1] }}
          SENDER: ${{ github.event.sender.login }}
        run: |
          MEMBER_CHECK=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $BOT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/PCL-Community/members/$SENDER")

          if [ "$MEMBER_CHECK" -ne 204 ]; then
            curl -X PATCH \
              -H "Authorization: token $BOT_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER" \
              -d '{"state_reason":"not_planned"}'

            curl -f -X DELETE \
              -H "Authorization: token $BOT_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
              -d '["❌ 拒绝 / 放弃","❌ 暂无计划","❌ 第三方","❌ 重复","⭕ 等待处理","😂 移交上游","🚧 正在处理"]'

            curl -f -X POST \
              -H "Authorization: token $BOT_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
              -d '{"labels":["❌ 忽略"]}'
          else
            curl -f -X DELETE \
              -H "Authorization: token $BOT_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
              -d '["❌ 忽略","❌ 拒绝 / 放弃","❌ 暂无计划","❌ 第三方","❌ 重复","⭕ 等待处理","😂 移交上游","🚧 正在处理"]'

            curl -f -X POST \
              -H "Authorization: token $BOT_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
              -d '{"labels":["👌 完成"]}'
          fi

      - name: Handle duplicate issue
        if: |
          github.event.issue.state_reason == 'duplicate' &&
          github.event.sender.login != 'PCL-Community-Bot'
        env:
          BOT_TOKEN: ${{ secrets.BOT }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository.split('/')[1] }}
        run: |
          curl -f -X DELETE \
            -H "Authorization: token $BOT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
            -d '["❌ 忽略","❌ 拒绝 / 放弃","❌ 暂无计划","❌ 第三方","👌 完成","⭕ 等待处理","😂 移交上游","🚧 正在处理"]'

          curl -f -X POST \
            -H "Authorization: token $BOT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
            -d '{"labels":["❌ 重复"]}'