name: Issue Closed
run-name: '#${{ github.event.issue.number }} ${{ github.event.issue.title }}'

on:
  issues:
    types: [closed]

jobs:
  close-as-completed:
    if: github.actor != 'PCL-Community-Bot' && github.event.issue.state_reason == 'completed'
    runs-on: ubuntu-latest
    steps:
      - name: Check permission
        id: check
        uses: actions-cool/check-user-permission@main
        with:
          token: '${{ secrets.BOT }}'
          require: 'write'

      - name: Add labels (with permission)
        if: steps.check.outputs.check-result == 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: '${{ secrets.BOT }}'
          labels: '👌 完成'

      - name: Add labels (without permission)
        if: steps.check.outputs.check-result == 'false'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: '${{ secrets.BOT }}'
          labels: '❌ 忽略'

      - name: Remove labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: '${{ secrets.BOT }}'
          labels: '⭕ 等待处理,🚧 正在处理,🕑 等待合并,🕑 等待前置'

  close-as-duplicate:
    if: github.actor != 'PCL-Community-Bot' && github.event.issue.state_reason == 'duplicate'
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: '${{ secrets.BOT }}'
          labels: '❌ 重复'

      - name: Remove labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: '${{ secrets.BOT }}'
          labels: '❌ 忽略,❌ 拒绝 / 放弃,❌ 暂无计划,❌ 第三方,⭕ 等待处理'

  close-as-not-planned:
    if: github.actor != 'PCL-Community-Bot' && github.event.issue.state_reason == 'not_planned' && !(contains(github.event.issue.labels.*.name, '❌') || contains(github.event.issue.labels.*.name, '😂'))
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: '${{ secrets.BOT }}'
          labels: '❌ 忽略'