name: Issue Closed

on:
  issues:
    types: [reopened]

jobs:
  issue-reopened:
    runs-on: ubuntu-latest
    steps:
      - name: Remove labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: '${{ secrets.BOT }}'
          labels: '👌 完成,❌ 忽略,❌ 拒绝 / 放弃,❌ 暂无计划,❌ 第三方,❌ 重复'